<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Admin Landing Page</title>
</head>
<body>
<%
    if ((session.getAttribute("user") == null)) {
%>
You are not logged in<br/>
<a href="AdminLogin.jsp">Please Login</a>
<%} else {
%>
 Welcome <%=session.getAttribute("user") %> 
 <br>***ONLY PICK ONE OPTION AT A TIME***<br>
<p style="float: right;"><a href="AdminLogout.jsp">Log out</a></p>
<br>

<form action="AdminFlightLog.jsp" method="POST">
	Retrieve list of all flights for an airport:
	<br><input type="text" name="airport_id" placeholder="Enter Airport"> 
	
	<form action="AdminFlightLog.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>

<form action="AdminSalesReport.jsp" method="POST">
	Sales report for all tickets with PURCHASE DATE in the month of: 
	<br>**month format is 01=January, 12=December
	<br><input type="text" name="month" placeholder="Enter Month"> 
	
	<form action="AdminSalesReport.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>

<form action="AdminFlightReservations.jsp" method="POST">
	Retrieve list of all reservations by flight number: 
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID"> <br>
	<input type="text" name="aircraft_id" placeholder="Enter Aircraft ID"> 
	
	<form action="AdminFlightReservations.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>

<form action="AdminRevByFlight.jsp" method="POST">
	Revenue generated by flight: 
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID"><br> 
	<input type="text" name="aircraft_id" placeholder="Enter Aircraft ID"> 
	
	<form action="AdminRevByFlight.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>

<form action="AdminRevByAirline.jsp" method="POST">
	Revenue generated by airline: 
	<br><input type="text" name="airline_id" placeholder="Enter Airline ID"> 
	
	<form action="AdminRevByAirline.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>

<form action="AdminRevByCustomer.jsp" method="POST">
	Revenue generated by customer: 
	<br><input type="text" name="userid" placeholder="Enter Customer Username"> 
	
	<form action="AdminRevByCustomer.jsp">
		<input type="submit" value="Retrieve">
	</form>	
</form>


<%
    }
%>
</body>
</html>